project:
  type: website

website:
  title: "Volkan Işık"
  navbar:
    left:
      - href: index.qmd
        text: Ana Sayfa
      - href: about.qmd
        text: Hakkımda
      - href: cv.qmd
        text: CV
      - href: blog.qmd
        text: Yazılar

format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto
