project:
  type: website
  resources:
    - publications.json

website:
  title: "Volkan Işık"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: cv.qmd
        text: CV
      - href: lectures.qmd
        text: Lectures
      - href: blog.qmd
        text: Blog
      - href: podcasts.qmd
        text: My Podcasts
      - href: events.qmd
        text: Upcoming Events
        

format:
  html:
    theme: cosmo
    css: styles.css
    include-in-header:
      - text: |
          <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" rel="stylesheet">

execute:
  freeze: auto
